[package]
name = "lattice-commitments"
version = "0.0.0"
edition = "2021"

[dependencies]
discrete-gaussian = "0.0.4"
rand = "0.8.5"
ring-math = "0.2.0"
scalarff = { version = "0.6.0", features = ["oxfoi", "random"] }

#ring-math = { path = "../ashlang/ring-math" }
